/* tslint:disable */
/* eslint-disable */
/**
 * Cultivate
 * test
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateListing201Response {
    '_id': string;
    'type': CreateListing201ResponseTypeEnum;
    'title': string;
    'item': string;
    'description': string;
    'price': number;
    'qty': number;
    'latLng': Array<any>;
    'createdBy': ListListings200ResponseInnerResponsesInnerCreatedBy;
    'matchedResponseId': string | null;
    'status': CreateListing201ResponseStatusEnum;
    'responses': Array<CreateListing201ResponseResponsesInner>;
    'createdAt': string;
    'updatedAt': string;
    'expiresAt': string | null;
}

export const CreateListing201ResponseTypeEnum = {
    Demand: 'demand',
    Supply: 'supply'
} as const;

export type CreateListing201ResponseTypeEnum = typeof CreateListing201ResponseTypeEnum[keyof typeof CreateListing201ResponseTypeEnum];
export const CreateListing201ResponseStatusEnum = {
    Open: 'open',
    Matched: 'matched',
    Fulfilled: 'fulfilled',
    Expired: 'expired'
} as const;

export type CreateListing201ResponseStatusEnum = typeof CreateListing201ResponseStatusEnum[keyof typeof CreateListing201ResponseStatusEnum];

export interface CreateListing201ResponseResponsesInner {
    '_id': string;
    'message': string;
    'price': number;
    'qty': number;
    'createdBy': ListListings200ResponseInnerResponsesInnerCreatedBy;
    'createdAt': string;
}
export interface CreateListingRequest {
    'type': CreateListingRequestTypeEnum;
    'title': string;
    'item': string;
    'description': string;
    'price': number;
    'qty': number;
    'unit'?: 'kg' | 'lb' | 'count' | 'bunch';
    'photos'?: Array<{ 'imageId': string }>;
    'expiresAt'?: string | null;
}

export const CreateListingRequestTypeEnum = {
    Demand: 'demand',
    Supply: 'supply'
} as const;

export type CreateListingRequestTypeEnum = typeof CreateListingRequestTypeEnum[keyof typeof CreateListingRequestTypeEnum];

export interface CreateListingResponseRequest {
    'message': string;
    'price': number;
    'qty': number;
    'unit'?: 'kg' | 'lb' | 'count' | 'bunch';
}
export interface Healthcheck200Response {
    'healthy': boolean;
    'time': any;
    'authenticated': boolean;
    'auth0Id'?: string;
}
export interface ListListings200ResponseInner {
    '_id': string | null;
    'type': ListListings200ResponseInnerTypeEnum;
    'title': string | null;
    'item': string | null;
    'description': string | null;
    'price': number;
    'qty': number;
    'unit'?: 'kg' | 'lb' | 'count' | 'bunch';
    'latLng': Array<any>;
    'createdBy': ListListings200ResponseInnerCreatedBy;
    'matchedResponseId': string | null;
    'status': ListListings200ResponseInnerStatusEnum;
    'responses': Array<ListListings200ResponseInnerResponsesInner>;
    'createdAt': string | null;
    'updatedAt': string | null;
    'expiresAt': string | null;
}

export const ListListings200ResponseInnerTypeEnum = {
    Demand: 'demand',
    Supply: 'supply'
} as const;

export type ListListings200ResponseInnerTypeEnum = typeof ListListings200ResponseInnerTypeEnum[keyof typeof ListListings200ResponseInnerTypeEnum];
export const ListListings200ResponseInnerStatusEnum = {
    Open: 'open',
    Matched: 'matched',
    Fulfilled: 'fulfilled',
    Expired: 'expired'
} as const;

export type ListListings200ResponseInnerStatusEnum = typeof ListListings200ResponseInnerStatusEnum[keyof typeof ListListings200ResponseInnerStatusEnum];

export interface ListListings200ResponseInnerCreatedBy {
    '_id': string | null;
    'name': string | null;
    'email': string | null;
}
export interface ListListings200ResponseInnerResponsesInner {
    '_id': string | null;
    'message': string | null;
    'price': number;
    'qty': number;
    'createdBy': ListListings200ResponseInnerResponsesInnerCreatedBy;
    'createdAt': string | null;
}
export interface ListListings200ResponseInnerResponsesInnerCreatedBy {
    '_id': string;
    'name': string;
    'email': string;
}
export interface ListUsers200ResponseInner {
    '_id': string | null;
    'name': string | null;
    'email': string | null;
    'role': ListUsers200ResponseInnerRoleEnum;
    'createdAt': string | null;
}

export const ListUsers200ResponseInnerRoleEnum = {
    Farmer: 'farmer',
    Restaurant: 'restaurant'
} as const;

export type ListUsers200ResponseInnerRoleEnum = typeof ListUsers200ResponseInnerRoleEnum[keyof typeof ListUsers200ResponseInnerRoleEnum];

export interface RegisterUser201Response {
    '_id': string | null;
    'name': string | null;
    'email': string | null;
    'role': RegisterUser201ResponseRoleEnum;
    'auth0Id': string | null;
    'avatar': string | null;
    'postalCode'?: string | null;
    'latLng'?: [number, number] | null;
    'createdAt': string | null;
}

export const RegisterUser201ResponseRoleEnum = {
    Farmer: 'farmer',
    Restaurant: 'restaurant'
} as const;

export type RegisterUser201ResponseRoleEnum = typeof RegisterUser201ResponseRoleEnum[keyof typeof RegisterUser201ResponseRoleEnum];

export interface RegisterUserRequest {
    'role': RegisterUserRequestRoleEnum;
    'postalCode': string;
}

export const RegisterUserRequestRoleEnum = {
    Farmer: 'farmer',
    Restaurant: 'restaurant'
} as const;

export type RegisterUserRequestRoleEnum = typeof RegisterUserRequestRoleEnum[keyof typeof RegisterUserRequestRoleEnum];

export interface UpdateUserRequest {
    'name'?: string;
    'email'?: string;
    'avatar'?: string | null;
    'postalCode'?: string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check route
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check route
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthcheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Healthcheck200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthcheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.healthcheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check route
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthcheck(options?: RawAxiosRequestConfig): AxiosPromise<Healthcheck200Response> {
            return localVarFp.healthcheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Health check route
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public healthcheck(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).healthcheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ListingsApi - axios parameter creator
 */
export const ListingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new listing (demand or supply)
         * @param {CreateListingRequest} [createListingRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListing: async (createListingRequest?: CreateListingRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createListingRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add a response (farmer offer) to an existing demand listing
         * @param {string} id 
         * @param {CreateListingResponseRequest} [createListingResponseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListingResponse: async (id: string, createListingResponseRequest?: CreateListingResponseRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createListingResponse', 'id', id)
            const localVarPath = `/listings/{id}/responses`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createListingResponseRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a single listing with its embedded responses
         * @param {string | null} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListing: async (id: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getListing', 'id', id)
            const localVarPath = `/listings/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all listings. Optional ?type=demand|supply filter. Returns creator info populated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listListings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/listings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListingsApi - functional programming interface
 */
export const ListingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ListingsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new listing (demand or supply)
         * @param {CreateListingRequest} [createListingRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createListing(createListingRequest?: CreateListingRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateListing201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createListing(createListingRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.createListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add a response (farmer offer) to an existing demand listing
         * @param {string} id 
         * @param {CreateListingResponseRequest} [createListingResponseRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createListingResponse(id: string, createListingResponseRequest?: CreateListingResponseRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateListing201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createListingResponse(id, createListingResponseRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.createListingResponse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a single listing with its embedded responses
         * @param {string | null} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListing(id: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateListing201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getListing(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.getListing']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all listings. Optional ?type=demand|supply filter. Returns creator info populated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listListings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListListings200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listListings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ListingsApi.listListings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ListingsApi - factory interface
 */
export const ListingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ListingsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new listing (demand or supply)
         * @param {ListingsApiCreateListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListing(requestParameters: ListingsApiCreateListingRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<CreateListing201Response> {
            return localVarFp.createListing(requestParameters.createListingRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add a response (farmer offer) to an existing demand listing
         * @param {ListingsApiCreateListingResponseRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createListingResponse(requestParameters: ListingsApiCreateListingResponseRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateListing201Response> {
            return localVarFp.createListingResponse(requestParameters.id, requestParameters.createListingResponseRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a single listing with its embedded responses
         * @param {ListingsApiGetListingRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListing(requestParameters: ListingsApiGetListingRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateListing201Response> {
            return localVarFp.getListing(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all listings. Optional ?type=demand|supply filter. Returns creator info populated.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listListings(options?: RawAxiosRequestConfig): AxiosPromise<Array<ListListings200ResponseInner>> {
            return localVarFp.listListings(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createListing operation in ListingsApi.
 */
export interface ListingsApiCreateListingRequest {
    readonly createListingRequest?: CreateListingRequest
}

/**
 * Request parameters for createListingResponse operation in ListingsApi.
 */
export interface ListingsApiCreateListingResponseRequest {
    readonly id: string

    readonly createListingResponseRequest?: CreateListingResponseRequest
}

/**
 * Request parameters for getListing operation in ListingsApi.
 */
export interface ListingsApiGetListingRequest {
    readonly id: string | null
}

/**
 * ListingsApi - object-oriented interface
 */
export class ListingsApi extends BaseAPI {
    /**
     * 
     * @summary Create a new listing (demand or supply)
     * @param {ListingsApiCreateListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createListing(requestParameters: ListingsApiCreateListingRequest = {}, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).createListing(requestParameters.createListingRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add a response (farmer offer) to an existing demand listing
     * @param {ListingsApiCreateListingResponseRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createListingResponse(requestParameters: ListingsApiCreateListingResponseRequest, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).createListingResponse(requestParameters.id, requestParameters.createListingResponseRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a single listing with its embedded responses
     * @param {ListingsApiGetListingRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getListing(requestParameters: ListingsApiGetListingRequest, options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).getListing(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all listings. Optional ?type=demand|supply filter. Returns creator info populated.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listListings(options?: RawAxiosRequestConfig) {
        return ListingsApiFp(this.configuration).listListings(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Return the authenticated user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List registered users (Auth0 IDs omitted)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Complete Auth0 registration by assigning a role
         * @param {RegisterUserRequest} [registerUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser: async (registerUserRequest?: RegisterUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Update the authenticated user's profile
         * @param {UpdateUserRequest} [updateUserRequest]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateCurrentUser: async (updateUserRequest?: UpdateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options };
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            await setBearerAuthToObject(localVarHeaderParameter, configuration);

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers };
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserRequest, localVarRequestOptions, configuration);

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Return the authenticated user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List registered users (Auth0 IDs omitted)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ListUsers200ResponseInner>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.listUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Complete Auth0 registration by assigning a role
         * @param {RegisterUserRequest} [registerUserRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerUser(registerUserRequest?: RegisterUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerUser(registerUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.registerUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        async updateCurrentUser(updateUserRequest?: UpdateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegisterUser201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateCurrentUser(updateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * 
         * @summary Return the authenticated user\'s profile
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<RegisterUser201Response> {
            return localVarFp.getCurrentUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List registered users (Auth0 IDs omitted)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(options?: RawAxiosRequestConfig): AxiosPromise<Array<ListUsers200ResponseInner>> {
            return localVarFp.listUsers(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Complete Auth0 registration by assigning a role
         * @param {UsersApiRegisterUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerUser(requestParameters: UsersApiRegisterUserRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RegisterUser201Response> {
            return localVarFp.registerUser(requestParameters.registerUserRequest, options).then((request) => request(axios, basePath));
        },
        updateCurrentUser(requestParameters: UsersApiUpdateCurrentUserRequest = {}, options?: RawAxiosRequestConfig): AxiosPromise<RegisterUser201Response> {
            return localVarFp.updateCurrentUser(requestParameters.updateUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updateCurrentUser operation in UsersApi.
 */
export interface UsersApiUpdateCurrentUserRequest {
    readonly updateUserRequest?: UpdateUserRequest;
}

/**
 * Request parameters for registerUser operation in UsersApi.
 */
export interface UsersApiRegisterUserRequest {
    readonly registerUserRequest?: RegisterUserRequest
}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI {
    /**
     * 
     * @summary Return the authenticated user\'s profile
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCurrentUser(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List registered users (Auth0 IDs omitted)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUsers(options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).listUsers(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Complete Auth0 registration by assigning a role
     * @param {UsersApiRegisterUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public registerUser(requestParameters: UsersApiRegisterUserRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).registerUser(requestParameters.registerUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    public updateCurrentUser(requestParameters: UsersApiUpdateCurrentUserRequest = {}, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateCurrentUser(requestParameters.updateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



